service: serverless-rest-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

# add 5 functions added for CURD operation
functions: 
  create:
    handler: handler.create
    events:
      - http: 
          path: notes
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http: 
          path: notes/{id}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events:
      - http: 
          path: notes
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http: 
          path: notes/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http: 
          path: notes/{id}
          method: delete
          cors: true
plugins:
- serverless-offline